Issue/quick 217 recommendations as artefacts
atlassian/jira-hardware-exploration pull request #57
Opened 2019-06-20 03:55 UTC by kema2000

2019-06-20 08:04 UTC, mminns approved these changes

2019-06-21 11:54 UTC, dagguh commented
Let's rebase to fix conflicts and let's get rid of that merge commit

2019-06-21 11:57 UTC, dagguh requested changes

2019-06-21 11:57 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/hardware/HardwareExploration.kt
> +                throw Exception("One or more tests failed : $failedHardware")
Let's rebase to fix conflicts and let's get rid of any merge commits

2019-06-21 12:10 UTC, dagguh commented on src/test/kotlin/com/atlassian/performance/tools/hardware/HardwareExploration.kt
> +                throw Exception("One or more tests failed : $failedHardware")
Ok, I did it and force-pushed it here

2019-06-21 12:38 UTC, dagguh approved these changes

2019-06-21 12:59 UTC, merged

2019-06-23 23:50 UTC, kema2000 commented
Thanks @dagguh